<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_barang_model extends CI_Model
{

    public $table = 't_barang';
    public $id = 'id_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_barang,nama_barang,kategori,harga,stok');
        $this->datatables->from('t_barang');
        //add this line for join
        //$this->datatables->join('table2', 't_barang.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/t_barang/read/$1'),'Read')." | ".anchor(site_url('admin/t_barang/update/$1'),'Update')." | ".anchor(site_url('admin/t_barang/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_barang');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('stok', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('stok', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_by_idkat($id)
    {
        $this->db->where("kategori", $id);
        return $this->db->get($this->table)->row();
    }

}

/* End of file T_barang_model.php */
/* Location: ./application/models/T_barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-16 15:13:07 */
/* http://harviacode.com */