<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_supplier_model extends CI_Model
{

    public $table = 't_supplier';
    public $id = 'id_supplier';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_supplier,nama_sup,tlp_sup,email_sup,alamat_sup');
        $this->datatables->from('t_supplier');
        //add this line for join
        //$this->datatables->join('table2', 't_supplier.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/t_supplier/read/$1'),'Read')." | ".anchor(site_url('admin/t_supplier/update/$1'),'Update')." | ".anchor(site_url('admin/t_supplier/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_supplier');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_supplier', $q);
	$this->db->or_like('nama_sup', $q);
	$this->db->or_like('tlp_sup', $q);
	$this->db->or_like('email_sup', $q);
	$this->db->or_like('alamat_sup', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_supplier', $q);
	$this->db->or_like('nama_sup', $q);
	$this->db->or_like('tlp_sup', $q);
	$this->db->or_like('email_sup', $q);
	$this->db->or_like('alamat_sup', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_supplier_model.php */
/* Location: ./application/models/T_supplier_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-22 17:36:24 */
/* http://harviacode.com */