<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_rekap_dtl_model extends CI_Model
{

    public $table = 'tbl_rekap_dtl';
    public $id = 'novcr';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($in) {
        $this->datatables->select('tbl_rekap_dtl.novcr,tbl_rekap_dtl.id_rekap,golongan,pagu,nama_tamu,checkin,checkout,type_room,harga_kamar,tagihan,service_fee,special,tbl_rekap.nospt,mak');
        $this->datatables->from('tbl_rekap_dtl');
        if($in){
            $this->datatables->where('id_rekap',$in);
        }
        //add this line for join
        $this->datatables->join('tbl_rekap', 'tbl_rekap_dtl.id_rekap = tbl_rekap.id_rekap');
        $this->datatables->add_column('action', anchor(site_url('admin/tbl_rekap_dtl/update/$1'),'Update')." | ".anchor(site_url('admin/tbl_rekap_dtl/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'novcr');
        return $this->datatables->generate();
    }
    
    function get_all($in)
    {
        $this->db->select('tbl_rekap_dtl.novcr,tbl_rekap_dtl.id_rekap,golongan,pagu,nama_tamu,checkin,checkout,type_room,harga_kamar,tagihan,tbl_rekap_dtl.service_fee,special,tbl_rekap.nospt,mak,date,view_pagu.nama_hotel,view_pagu.kota,alamat,telepon,confirm');
        $this->db->from($this->table);
        //add this line for join
        $this->db->join('tbl_rekap', 'tbl_rekap_dtl.id_rekap = tbl_rekap.id_rekap');
        $this->db->join('view_pagu', 'tbl_rekap.id_hotel = view_pagu.id_hotel');
        if($in){
            $this->db->where("tbl_rekap_dtl.id_rekap", $in);
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }
    
    function get_by_idnew($in)
    {
        $this->db->select('tbl_rekap_dtl.novcr,tbl_rekap_dtl.id_rekap,golongan,pagu,nama_tamu,checkin,checkout,type_room,harga_kamar,tagihan,tbl_rekap_dtl.service_fee,special,tbl_rekap.nospt,mak,date,view_pagu.nama_hotel,kota,alamat,telepon,confirm');
        $this->db->from($this->table);
        //add this line for join
        $this->db->join('tbl_rekap', 'tbl_rekap_dtl.id_rekap = tbl_rekap.id_rekap');
        $this->db->join('view_pagu', 'tbl_rekap.id_hotel = view_pagu.id_hotel');
        if($in){
            $this->db->where("tbl_rekap_dtl.novcr", $in);
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('novcr', $q);
	$this->db->or_like('id_rekap', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('pagu', $q);
	$this->db->or_like('nama_tamu', $q);
	$this->db->or_like('checkin', $q);
	$this->db->or_like('checkout', $q);
	$this->db->or_like('type_room', $q);
	$this->db->or_like('harga_kamar', $q);
	$this->db->or_like('tagihan', $q);
	$this->db->or_like('service_fee', $q);
	$this->db->or_like('special', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('novcr', $q);
	$this->db->or_like('id_rekap', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('pagu', $q);
	$this->db->or_like('nama_tamu', $q);
	$this->db->or_like('checkin', $q);
	$this->db->or_like('checkout', $q);
	$this->db->or_like('type_room', $q);
	$this->db->or_like('harga_kamar', $q);
	$this->db->or_like('tagihan', $q);
	$this->db->or_like('service_fee', $q);
	$this->db->or_like('special', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_rekap_dtl_model.php */
/* Location: ./application/models/Tbl_rekap_dtl_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-03 04:27:17 */
/* http://harviacode.com */