<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_provinsi_model extends CI_Model
{

    public $table = 'tbl_provinsi';
    public $id = 'id_prov';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_prov,nama_prov,satuan,eselon1,eselon2,golongan4,golongan321');
        $this->datatables->from('tbl_provinsi');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_provinsi.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/tbl_provinsi/read/$1'),'Read')." | ".anchor(site_url('admin/tbl_provinsi/update/$1'),'Update')." | ".anchor(site_url('admin/tbl_provinsi/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_prov');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_prov', $q);
	$this->db->or_like('nama_prov', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('eselon1', $q);
	$this->db->or_like('eselon2', $q);
	$this->db->or_like('golongan4', $q);
	$this->db->or_like('golongan321', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_prov', $q);
	$this->db->or_like('nama_prov', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('eselon1', $q);
	$this->db->or_like('eselon2', $q);
	$this->db->or_like('golongan4', $q);
	$this->db->or_like('golongan321', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_provinsi_model.php */
/* Location: ./application/models/Tbl_provinsi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-30 13:24:14 */
/* http://harviacode.com */