<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_rekap_model extends CI_Model
{

    public $view = 'view_pagu';
    public $table = 'tbl_rekap';
    public $id = 'id_rekap';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('tbl_rekap.id_rekap,tanggal,nospt,mak,tbl_rekap.id_hotel,total_tagihan,service_fee,date,by,tbl_hotel.nama_hotel,users.first_name');
        $this->datatables->from('tbl_rekap');
        //add this line for join
        $this->datatables->join('tbl_hotel', 'tbl_rekap.id_hotel = tbl_hotel.id_hotel');
        $this->datatables->join('users', 'tbl_rekap.by = users.id');
        $this->datatables->add_column('action', anchor(site_url('admin/tbl_rekap/update/$1'),'Update')." | ".anchor(site_url('admin/tbl_rekap_dtl/index/$1'),'Detail')." | ".anchor(site_url('admin/tbl_rekap/delete/$1'),'Hapus','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_rekap');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get data by id
    function get_by_viewid($id)
    {
        $this->db->where('id_hotel', $id);
        return $this->db->get($this->view)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_rekap', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nospt', $q);
	$this->db->or_like('mak', $q);
	$this->db->or_like('id_hotel', $q);
	$this->db->or_like('total_tagihan', $q);
	$this->db->or_like('service_fee', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('by', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_rekap', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nospt', $q);
	$this->db->or_like('mak', $q);
	$this->db->or_like('id_hotel', $q);
	$this->db->or_like('total_tagihan', $q);
	$this->db->or_like('service_fee', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('by', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_rekap_model.php */
/* Location: ./application/models/Tbl_rekap_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-03 04:27:10 */
/* http://harviacode.com */