<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_hotel_model extends CI_Model
{

    public $table = 'tbl_hotel';
    public $id = 'id_hotel';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_hotel,nama_hotel,kota,alamat,telepon,id_prov,confirm,group');
        $this->datatables->from('tbl_hotel');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_hotel.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/tbl_hotel/read/$1'),'Read')." | ".anchor(site_url('admin/tbl_hotel/update/$1'),'Update')." | ".anchor(site_url('admin/tbl_hotel/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_hotel');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_hotel', $q);
	$this->db->or_like('nama_hotel', $q);
	$this->db->or_like('kota', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('id_prov', $q);
	$this->db->or_like('confirm', $q);
	$this->db->or_like('group', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_hotel', $q);
	$this->db->or_like('nama_hotel', $q);
	$this->db->or_like('kota', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('id_prov', $q);
	$this->db->or_like('confirm', $q);
	$this->db->or_like('group', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_hotel_model.php */
/* Location: ./application/models/Tbl_hotel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-03 04:27:05 */
/* http://harviacode.com */