<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_laporan_masuk extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T_barang_masuk_model');
        $this->load->model('T_barang_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'Laporan Barang Masuk');
        $this->template->load('template','admin/t_barang_masuk/t_laporan_masuk_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->T_barang_masuk_model->json();
    }

    public function read($id) 
    {
        $row = $this->T_barang_masuk_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_bm' => $row->id_bm,
		'tgl_bm' => $row->tgl_bm,
		'id_barang' => $row->id_barang,
		'nama_barang' => $row->nama_barang,
		'jml_bm' => $row->jml_bm,
		'harga_bm' => $row->harga_bm,
		'sub_total_bm' => $row->sub_total_bm,
        'id_supplier' => $row->id_supplier,
	    );
            $this->template->load('template','admin/t_barang_masuk/t_barang_masuk_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/t_barang_masuk'));
        }
    }

    public function view($in=""){
        $row = $this->T_barang_masuk_model->get_all_join();
        if (@$row) {
            $data = array('data' => $row);
            $this->load->view('admin/t_barang_masuk/t_barang_masuk_cetak',$data);
        }
    }

    public function cetak($in=""){
        $row = $this->T_barang_masuk_model->get_all_join();
        if (@$row) {
            $mpdf = new \Mpdf\Mpdf();
            $data = array('data' => $row);
            $html = $this->load->view('admin/t_barang_masuk/t_barang_masuk_cetak',$data,true);
            $mpdf->AddPage('L', // L - landscape, P - portrait
            '', '', '', '',
            10, // margin_left
            10, // margin right
            20, // margin top
            10, // margin bottom
            18, // margin header
            12); // margin footer
            $mpdf->WriteHTML($html);
            $mpdf->Output(date('ymd_His').'laporan_barang_masuk'.$in.'_t_'.'.pdf', 'I');
        } 
        redirect(site_url('admin/t_laporan_masuk/index/'.$in));
    }
}

/* End of file T_barang_masuk.php */
/* Location: ./application/controllers/T_barang_masuk.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-13 17:53:23 */
/* http://harviacode.com */