<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_stokbarang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T_barang_model');
        $this->load->library('form_validation');        
       $this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'Barang');
        $this->template->load('template','admin/t_barang/t_stokbarang_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->T_barang_model->json();
    }

    public function view($in=""){
        $row = $this->T_barang_model->get_all();
        if (@$row) {
            $data = array('data' => $row);
            $this->load->view('admin/t_barang/t_barang_cetak',$data);
        }
    }

    public function cetak($in=""){
        $row = $this->T_barang_model->get_all();
        if (@$row) {
            $mpdf = new \Mpdf\Mpdf();
            $data = array('data' => $row);
            $html = $this->load->view('admin/t_barang/t_barang_cetak',$data,true);
            $mpdf->AddPage('L', // L - landscape, P - portrait
            '', '', '', '',
            10, // margin_left
            10, // margin right
            20, // margin top
            10, // margin bottom
            18, // margin header
            12); // margin footer
            $mpdf->WriteHTML($html);
            $mpdf->Output(date('ymd_His').'stok_barang'.$in.'_t_'.'.pdf', 'I');
        } 
        redirect(site_url('admin/t_stokbarang/index/'.$in));
    }

}

/* End of file T_barang.php */
/* Location: ./application/controllers/T_barang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-16 15:13:07 */
/* http://harviacode.com */