<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_tamu extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_tamu_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'tbl_tamu');
        $this->template->load('template','admin/tbl_tamu/tbl_tamu_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_tamu_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_tamu_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_tamu' => $row->id_tamu,
		'nama_tamu' => $row->nama_tamu,
		'daftar_tamu' => $row->daftar_tamu,
	    );
            $this->template->load('template','admin/tbl_tamu/tbl_tamu_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/tbl_tamu'));
        }
    }

    public function create() 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/tbl_tamu/create_action'),
	    'id_tamu' => set_value('id_tamu'),
	    'nama_tamu' => set_value('nama_tamu'),
	    'daftar_tamu' => set_value('daftar_tamu'),
	);
        $this->template->load('template','admin/tbl_tamu/tbl_tamu_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_tamu' => $this->input->post('nama_tamu',TRUE),
		'daftar_tamu' => $this->input->post('daftar_tamu',TRUE),
	    );

            $this->Tbl_tamu_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/tbl_tamu'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_tamu_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/tbl_tamu/update_action'),
		'id_tamu' => set_value('id_tamu', $row->id_tamu),
		'nama_tamu' => set_value('nama_tamu', $row->nama_tamu),
		'daftar_tamu' => set_value('daftar_tamu', $row->daftar_tamu),
	    );
            $this->template->load('template','admin/tbl_tamu/tbl_tamu_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/tbl_tamu'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_tamu', TRUE));
        } else {
            $data = array(
		'nama_tamu' => $this->input->post('nama_tamu',TRUE),
		'daftar_tamu' => $this->input->post('daftar_tamu',TRUE),
	    );

            $this->Tbl_tamu_model->update($this->input->post('id_tamu', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/tbl_tamu'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_tamu_model->get_by_id($id);

        if ($row) {
            $this->Tbl_tamu_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/tbl_tamu'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/tbl_tamu'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_tamu', 'nama tamu', 'trim|required');
	$this->form_validation->set_rules('daftar_tamu', 'daftar tamu', 'trim|required');

	$this->form_validation->set_rules('id_tamu', 'id_tamu', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tbl_tamu.php */
/* Location: ./application/controllers/Tbl_tamu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-29 03:38:36 */
/* http://harviacode.com */