<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Order_model');
        $this->load->model('Web_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
        $this->load->model('T_barang_model');
    }

    public function index()
    {
        $data = array(
            'title' => 'Transaksi',
        );
        $this->template->load('template','admin/order/transaksi', $data);
    } 
    
    public function tabel()
    {
        $a = $this->input->post('a',TRUE);
        $barang = $this->input->post('b',TRUE);
        $row = $this->T_barang_model->get_by_id($barang);
        $this->deklar($barang);
        foreach($this->cart->contents() as $key) { 
            if ($key['id']==$barang) {
                $rowid = $key['rowid'];
            }
        }
        ?>
        <td>
            <input type="hidden" name="rowid[]" class="form-control" value="<?= $rowid?>"/>
            <input type="hidden" name="id[]" class="form-control" value="<?= $row->id_barang?>"/>
            <input type="hidden" name="kategori[]" class="form-control" value="<?= $row->kategori?>"/>
            <input type="text" name="name[]" class="form-control" value="<?= $row->nama_barang?>" readonly/>
        </td>
        <td>
            <input type="number" name="price[]" class="form-control" id="harga_jual<?= $a?>" value="<?= $row->harga?>" mk<?= $a?>="<?= $a?>" readonly/>
        </td>
        <td>
            <input type="number" name="qty[]" class="form-control" id="qtys<?= $a?>" value="1" min="0" onchange="plus(this.value,<?= $a?>,'<?= $rowid?>')"  />
        </td>
        <td>
            <input type="number" name="subtotal[]" class="form-control" id="subtototal<?= $a?>" value="<?= $row->harga?>" readonly>
        </td>
        <td><a href="#" onclick="hapus2(this,'<?= $rowid?>')">Hapus</a></td>
        <?php
    }

    public function deklar($id)
    {
        $row = $this->T_barang_model->get_by_id($id);
        $kategori = $this->T_barang_model->get_by_idkat($row->kategori);
        $datas= array(
            'id' => $id,
            'name' => $row->nama_barang,
            'price' => $row->harga,
            'qty' => 1,
            'kategori' => $kategori->kategori,
        );
        $this->cart->product_name_rules = '[:print:]';
        $this->cart->insert($datas);
    }

    public function hapus_cart(){ //fungsi untuk menghapus item cart
        $row_id = $this->input->post('row_id',TRUE);
        $rp = array(
            'value' => $this->cart->contents()[$row_id],
        );
        $this->cart->remove($row_id);
        $rp['nilai'] = $this->cart->total();
        echo(json_encode($rp));
    }  

    public function update_cart($a,$b)
    {
        $data = array(
            'rowid' => $a,
            'qty' => $b,
        );
        $this->cart->update($data);
        $rp = array(
            'format' => $this->cart->format_number($this->cart->total()),
            'nilai' => $this->cart->total()
        );
        echo(json_encode($rp));
    }
}

/* End of file Order.php */
/* Location: ./application/controllers/Order.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-17 08:36:58 */
/* http://harviacode.com */